# Generated by Django 5.0.1 on 2024-01-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_address', models.TextField()),
                ('client_gstin', models.CharField(max_length=50)),
                ('client_contact_details', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('service_accounting_code', models.CharField(max_length=20)),
                ('description_of_service', models.CharField(max_length=255)),
                ('hours_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_value_inr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
