# Generated by Django 5.0.1 on 2024-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='GT20240001', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
