# Generated by Django 5.0.1 on 2024-01-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoice_no_invoice_tax_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_country',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_statecode',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
