# Generated by Django 5.0.1 on 2024-01-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_client_country_invoice_client_statecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
